version: '3.8'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - "./config/conf.d:/etc/nginx/conf.d"
    links:
      - app
  app:
    image: node:13.14.0
    container_name: app
    hostname: app
    volumes:
      - "./next:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"

